### ISSUE TITLE
Video download not work

### ISSUE THREAD

**Issue by Lenushta** [CoolmanCZ/rajce#13]
I have downloaded version v1.5.13 but videos download not work. I have checked "Stahovat video soubory" and it looks like videos are downloading but in folder is only photos.

**Comment by CoolmanCZ** [comment]
Hi, can you check the version 1.5.15?

**Comment by Lenushta** [comment]
> 
> 
> Hi, can you check the version 1.5.15?

Děkuji za rychlou reakci. Verze 1.5.15 je trochu lepší, většinu videí mi to nyní již stáhlo, ale některá stále ne. Myslím že by to mohlo být způsobeno názvem souboru. Videa s názvem _"V kosmické raketě" a čekání na oběd.mp4_ a _"V kosmické raketě".mp4_ to nestahlo ačkoli to zobrazuje že se stahují a video s názvem _Úkol č.6: Naučte se, zatancujte a zazpívejte písničku "Žabička zelená".mp4_ to stáhne jako složku s názvem _Úkol č.6_. Možná problém s uvozovkami v názvu? Videa, která to stahla v pořádku uvozovky v názvu neměli.

**Comment by CoolmanCZ** [comment]
Is it possible to get link to the album with these names?

**Comment by Lenushta** [comment]
> 
> 
> Is it possible to get link to the album with these names?

I create test album with same problems. "V kosmické raketě", etc. isn't name of uploaded file. It is description of video and downloader use it as file name, but apostrophe isn't allowed character

https://lenkazoul.rajce.idnes.cz/test/
jméno: test 
kód:1234

**Comment by CoolmanCZ** [comment]
Hi, I can see the problem - Windows doesn't allow to use these characters \/:*?:<>|. So I will use the file name used by rajce.net in their storage (without these characters) for storing video files.

**Comment by Kul54321** [comment]
Hi, in the Rojce Downloader versions 1.5.19 does not work an option for appending the user name to download directory. In the older versions which were running on Win7, the downloader created a folder for a particular Rajce user and then kept downloading the albums of that user to that folder under separate folders, to which it attached the particular album name. Since this feature does not work in the later and even in the latest releases, it is possible to get only the name of the album without the needed references to the Rajce user. Could tis be fixed? I am not knowledgeable in coding and this stuff at all. Would appreciate if you could fix this problem. Perhaps finding why it does not function in Version 1.5.19. Thanks.

**Comment by CoolmanCZ** [comment]
Hi Kul54321, Rajce.net changed the access to albums a little (more to password protected albums), which would require a bigger change in the code. And since I don't plan to add more functionality or adapt Downloader to these changes, I have to decline your request.
