### ISSUE TITLE
set directory issue

### ISSUE THREAD

**Issue by zssnode** [CoolmanCZ/rajce#4]
if i set path to other directory . when i close  and reopen it, it  will reset to default directory
other issue , if i set path to other directory( not during download), when i download , it will download in default directory, not in my chose directory ,need to abort and redownload ， then it can download pics in my chose directory

**Comment by CoolmanCZ** [comment]
Hi,

This is a simple application and it doesn't have the configuration file to store last selected directory for download. So the default directory is always used.

Changing the download directory during download is not possible because all downloaded picture has defined download directory before the download has started. I'll disable this possibility in next release.

BR, Radek

**Comment by CoolmanCZ** [comment]
Store settings to the configuration file is available via d432bd8.
